---
title: "Demographic Table"
order: 2
---

## Data Setup

```{r setup, message=FALSE, warning=FALSE, results='hold'}}
#| code-fold: show

library(tern)
library(dplyr)

adsl <- tern_ex_adsl %>%
  df_explicit_na()

# Create categorical variables
adsl <- adsl %>%
  mutate(
    SEX = factor(case_when(
      SEX == "M" ~ "Male",
      SEX == "F" ~ "Female",
      SEX == "U" ~ "Unknown",
      SEX == "UNDIFFERENTIATED" ~ "Undifferentiated"
    )),
    AGEGR1 = factor(
      case_when(
        between(AGE, 18, 40) ~ "18-40",
        between(AGE, 41, 64) ~ "41-64",
        AGE > 64 ~ ">=65"
      ),
      levels = c("18-40", "41-64", ">=65")
    ),
    BMRKR1_CAT = factor(
      case_when(
        BMRKR1 < 3.5 ~ "LOW",
        BMRKR1 >= 3.5 & BMRKR1 < 10 ~ "MEDIUM",
        BMRKR1 >= 10 ~ "HIGH"
      ),
      levels = c("LOW", "MEDIUM", "HIGH")
    )
  )
```

## Demographic table

```{r table}
vars <- c("AGE", "AGEGR1", "SEX", "RACE", "BMRKR1", "BMRKR1_CAT")
var_labels <- c(
  "Age (yr)",
  "Age group",
  "Sex",
  "Race",
  "Continous Level Biomarker 1",
  "Categorical Level Biomarker 1"
)

lyt <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by(var = "ACTARM") %>%
  add_overall_col("All Patients") %>%
  analyze_vars(
    vars = vars,
    var_labels = var_labels
  )

result <- build_table(lyt, adsl)

result
```